<?php if ($this->pageCount > 1) : ?>
    <nav area-label="page navigation">
        <ul class="pagination">
            <li>
                <a href="<?php echo $this->url($this->route, array('page' => $this->previous) + $this->routeParams); ?>">
                    <span area-hidden="true">&laquo;</span>
                </a>
            </li>
            <?php foreach ($pagesInRange as $page): ?>
                <li>
                    <?php if ($page != $this->current): ?>
                        <a href="<?php echo $this->url($this->route, array('page' => $page) + $this->routeParams); ?>"><?php echo $page; ?></a>
                    <?php else: ?>
                        <span class="active"><?php echo $page; ?></span>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
            <li>
                <a href="<?php echo $this->url($this->route, array('page' => $this->next) + $this->routeParams); ?>">
                    <span area-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
<?php endif; ?>